### ISSUE TITLE
怎么部署到其他云环境中，如阿里云、unicloud？

### ISSUE THREAD

**Issue by Godow** [TencentCloudBase/cloudbase-framework#120]
**这个功能提议是否涉及到某个问题，请详细描述**
**Is your feature request related to a problem? Please describe. **

请对您遇到问题进行清楚、简洁的描述，比如我遇到一个问题，当我...

**描述您期望的解决方案**
**Describe the solution you'd like**

请详细描述您预期的效果

**您认为可以接受的备选解决方案**
**Describe alternatives you've considered**

请详细描述您希望的备选解决方案。

**其他上下文信息**
**Additional context**

关于这个新功能提议，您可以添加一些上下文信息或者截图信息。

**Comment by binggg** [comment]
暂不支持，如果后续有需求，可以根据底层产生的描述文件 SAM（Serverless Applacation Model）开发对应的云资源提供商的部署实现

**Comment by binggg** [comment]
另外，在云托管场景下，本质上是基于 Dockerfile，可以跨云厂商进行迁移

**Comment by Godow** [comment]
> 暂不支持，如果后续有需求，可以根据底层产生的描述文件 SAM（Serverless Applacation Model）开发对应的云资源提供商的部署实现

那有没有办法我用unicloud的云函数，云存储之类，但是在腾讯云开通cms对unicloud进行管理。当然，unicoud使用的也是腾讯云，但是两者的环境似乎没有任何关联。

**Comment by binggg** [comment]
如果你可以登录unicloud 开通的云开发的腾讯云账号，就可以在控制台进行安装CMS来管理

**Comment by binggg** [comment]
可以找 UniCloud 咨询下如何登录腾讯云控制台进行管理

**Comment by binggg** [comment]
或者如果有 UniCloud 对应的腾讯云的API密钥
也可以使用 CloudBase Framework 来直接部署一个 CMS
https://github.com/TencentCloudBase/cloudbase-extension-cms

**Comment by Godow** [comment]
感谢

**Comment by binggg** [comment]
不客气，Issue 我先关闭了，后续可以继续提问，或者入群交流

**Comment by Godow** [comment]
好的
