### ISSUE TITLE
部署配置文件在老环境部署成功，新建环境，换个env id就部署失败了

### ISSUE THREAD

**Issue by ashuihui** [TencentCloudBase/cloudbase-framework#2]
部署配置文件在老环境部署成功，新建环境，换个env id就部署失败了
Error: 部署失败，错误信息：[100001]pay Mode[PREPAYMENT] != EnvType[PostPay]， 请求RequestId：72d7a44b-3895-4b92-b4a1-478f2d0d1140

**Comment by binggg** [comment]
看报错信息，新建的环境不是按量付费的，网站部署目前只支持在按量付费环境开通，可以转下付费方式

**Comment by ashuihui** [comment]
> 看报错信息，新建的环境不是按量付费的，网站部署目前只支持在按量付费环境开通，可以转下付费方式

可我是部署函数和数据库啊
