### ISSUE TITLE
nuxt ssr 能不能提供ts模板

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-framework#3]
我想用typescript来写，但是用nuxt官方创建的ts项目集成不了云开发

**Comment by binggg** [comment]
@DaZiYuan 这个是解决了么

**Comment by DaZiYuan** [comment]
还在自己折腾中，官方有教材或模板的话更好了。。

**Comment by binggg** [comment]
我们也看看这个问题



---原始邮件---
发件人: "代码抄写狮"<notifications@github.com&gt;
发送时间: 2020年7月3日(周五) 下午4:44
收件人: "TencentCloudBase/cloudbase-framework"<cloudbase-framework@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Booker Zhao"<being99@qq.com&gt;;
主题: Re: [TencentCloudBase/cloudbase-framework] nuxt ssr 能不能提供ts模板 (#3)




 
还在自己折腾中，官方有教材或模板的话更好了。。
