### ISSUE TITLE
Vue模板创建的项目web端怎那么获取uid

### ISSUE THREAD

**Issue by chatterzhao** [TencentCloudBase/cloudbase-framework#41]
我使用cloudbase init --template vue 创建了项目，我用的匿名登录，我有点初级，我获取不到uid，只能获取到token。原生的HTML，js我捣鼓了能获取到uid，代码为：app.auth().hasLoginState().user.uid，哪位朋友能帮忙给一段这个vue 模板下怎么获取到uid的代码，万分感谢！

**Comment by binggg** [comment]
可以看下这个文档
https://github.com/TencentCloudBase/cloudbase-vue#vuecloudbase

**Comment by chatterzhao** [comment]
可能是我基础有点弱，我还是没get 获取uid的方法

另外看到您给我分享的教程，我看到获取云存储真实url的代码为：
<CloudFile
id="cloud://file-cloud-path"
v-slot="{ url, loading }"

{{ url ? url : 'loading...' }}
这是不是说，在 Vue 中用这个代替 cloud.getTempFileURL()

**Comment by binggg** [comment]
CloudFile  这个方便些

this.$cloudbase 就相当于 app
所以可以 this.$cloudbase.auth().hasLoginState().user.uid

**Comment by chatterzhao** [comment]
我这里 this.$cloudbase.auth().hasLoginState()下面就只有accesstoken和refreshtoken，没有user什么的

**Comment by binggg** [comment]
@chatterzhao 这里是因为Vue 插件的版本依赖的tcb-js-sdk 没有升级，我们处理下

**Comment by chatterzhao** [comment]
@binggg 非常感谢

**Comment by binggg** [comment]
已解决，可以升级 @cloudbase/vue-provider 到 0.3.0

基于 CLI 创建新的 vue 相关的模板也已经更新了
