### ISSUE TITLE
egg-starter 示例部署后无法访问

### ISSUE THREAD

**Issue by datoulei** [TencentCloudBase/cloudbase-framework#48]
问题描述
  部署后访问链接返回如下数据：
{
"requestId": "0e6d4281196d94ab9be1af0f0dde452f",
"code": "INVOKE_FUNCTION_FAILED",
"message": "user’s issue failed:kLoadFuncFailed"
}

目前发现 express、koa应用部署后可以直接访问， nest、egg部署后无法访问。
  
重现步骤
1. tcb init 
2. 选择环境，选择egg框架
3. 进入egg-starter目录
4. 执行 tcb framework:deploy
5. 访问云接入提供的链接

**Comment by binggg** [comment]
收到，我们排查下

**Comment by binggg** [comment]
@datoulei 帮忙查看下 CLI 的版本
 tcb -v

我刚才试了下 egg-starter 没有重现

**Comment by datoulei** [comment]
> @datoulei 帮忙查看下 CLI 的版本
> tcb -v
> 
> 我刚才试了下 egg-starter 没有重现

当前tcb版本是 0.9.1

**Comment by binggg** [comment]
试了下相同版本没有重现，方便的话可以进QQ群交流771895625

**Comment by binggg** [comment]
@datoulei 可以试试 @cloudbase/cli@0.9.3 版本

**Comment by binggg** [comment]
建议
npm i @cloudbase/cli@latest -g
然后删除 ~/cloudbase-framework/ 目录
再重试下
