### ISSUE TITLE
eggjs部署

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-framework#5]
希望增加对eggjs的插件支持！

**Comment by chhpt** [comment]
@juukee 已经在做支持了，本周发布，欢迎关注。

**Comment by chenhui7373** [comment]
> @juukee 已经在做支持了，欢迎支持关注

请做 midwayjs 支持吧，借用midway-faas能力

**Comment by binggg** [comment]
已经支持

cloudbase init --template egg-starter
