### ISSUE TITLE
windows的linux子系统，报错 spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by seolhw** [TencentCloudBase/cloudbase-framework#58]
windows的linux子系统，报错 spawn cmd.exe ENOENT

![image](https://user-images.githubusercontent.com/45996179/89756248-82e38880-db14-11ea-8535-cd453ae153d5.png)

**Comment by binggg** [comment]
收到，我们排查下

**Comment by chhpt** [comment]
@seolhw Windows 子系统不支持通过浏览器授权，请使用腾讯云-云 API 密钥授权登录：https://docs.cloudbase.net/cli/intro.html#deng-lu
