### ISSUE TITLE
【cloudbase-node-builder】当 entry 不在根目录时，需要读取 entry 对应的 pacakge.json 的依赖

### ISSUE THREAD

**Issue by zemzheng** [TencentCloudBase/cloudbase-framework#6]
## 现状
```
+ project 
  - cloudbaserc.json
  - package.json
  + subproject
    - package.json
    - entry.js
```
- 使用上面这个 subproject 的时候，应该期待使用 subproject/package.json 里面的依赖
- 但是目前直接去拉取 project/package.json

## 修改
- 先判断有没有最近的 package.json
- 再逐步追溯到上层 pacakge.json

**Comment by binggg** [comment]
@all-contributors please add @binggg

**Comment by binggg** [comment]
@all-contributors please add @binggg  for infrastructure, tests and code
