### ISSUE TITLE
云开发日志无法保存配置

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-framework#74]
![image](https://user-images.githubusercontent.com/28680837/90995406-72d8a800-e5ee-11ea-9ef7-f514a092b7f3.png)
![image](https://user-images.githubusercontent.com/28680837/90995423-86840e80-e5ee-11ea-9152-42a5bb88f525.png)
1.如图，设置保存以后日志采集路径依然为空，保存无效！！
2.希望在配置文件增加日志采集路径的配置选项.

**Comment by binggg** [comment]
后端反馈已解决
