### ISSUE TITLE
从代码库拉取的版本一直处于更新中

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-framework#75]
![image](https://user-images.githubusercontent.com/28680837/90995545-cc40d700-e5ee-11ea-8389-0dd3a6d30be1.png)
如图，如果版本是从代码库拉取的，如果一旦代码库更新，则镜像版本会处于一直更新中的状态，无法操作，无法删除停止。

**Comment by binggg** [comment]
后端反馈已解决

@all-contributors please add @juukee  for bug

感谢 @juukee 反馈贡献
